spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/logistics?serverTimezone=GMT%2B8&characterEncoding=utf-8&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

mybatis-plus:
  #扫描sql映射文件文件
  mapper-locations: classpath:/mapper/*.xml
  #主键自增
  global-config:
    db-config:
      id-type: auto

pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

logging:
  level:
    com.ev.logistics: debug